### ISSUE TITLE
dowstream/upstream events

### ISSUE THREAD

**Issue by vladsavelyev** [AstraZeneca-NGS/simple_sv_annotation#6]
This clause seems to be never reached as it's covered by the "gene_fusion" `elif` above: https://github.com/AstraZeneca-NGS/simple_sv_annotation/blob/master/simple_sv_annotation.py#L138

Also a more theoretical question - why checking downstream/upstream events? Because SnpEFF fails to call as fusions events like when a gene is inserted downstream and got into a control of another gene's promoter? Couldn't find an explanation in the manuscript.

**Comment by chapmanb** [comment]
I'll have to defer to @mjafin on his thought process on adding this. Since it doesn't actually get reached, it sounds like it's not having the intended effect anyways. I'd worry about this pulling in a lot of additional false positives, so think it might be a good outcome that this doesn't currently add in a large number of these events.

**Comment by vladsavelyev** [comment]
If I'm understanding the code correctly, it won't produce more annotations, but less. The code roughly looks like this:

```
if fusion or downstream or upstream:
   <prioritize>
elif downstream or upstream:
   <prioritize if in target genes>
```

So effectively _all_ downstream/upstream mutations are prioritized among with fusions in the first `if` clause.

Would be nice to hear Miika's thoughts. But nothing critical: in practice I don't see a lot of downstream/upstream events, so I think it's fine to leave it like this.

**Comment by mjafin** [comment]
Hi Vlad and Brad,
It's been some time since I looked at this code but it seems like the line at 
https://github.com/AstraZeneca-NGS/simple_sv_annotation/blob/master/simple_sv_annotation.py#L131
shouldn't have the ` or "downstream" in ann_a[1] or "upstream" in ann_a[1]`. Rather the upstream/downstream events should be handled at https://github.com/AstraZeneca-NGS/simple_sv_annotation/blob/master/simple_sv_annotation.py#L138 where like Vlad says only upstream/downstream events of prioritised genes should be considered

Edit. I'm happy for you to make the above fix Vlad or try doing it myself, let me know. As to why we'd like to flag up upstream/downstream events there was a reason but it escapes me totally. Maybe it's like you say they might affect the promoters of genes like BRCA1/2 and throw them off.

**Comment by vladsavelyev** [comment]
Thanks so much for looking into this Miika, that makes sense! I can make a pull request.
